CREATE DATABASE filmes;

USE filmes;

CREATE TABLE genero(
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nome VARCHAR(30) NOT NULL
);

CREATE TABLE atores(
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nome VARCHAR(50) NOT NULL
);

CREATE TABLE filmes (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    genero_id INT UNSIGNED NOT NULL,  
    FOREIGN KEY (genero_id) REFERENCES genero(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE atores_filmes(
    filme_id INT UNSIGNED NOT NULL,
    ator_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (filme_id) REFERENCES filmes(id) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (ator_id) REFERENCES atores(id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (filme_id, ator_id)
);

INSERT INTO genero (nome) VALUES ('Comedia');
INSERT INTO filmes (nome,genero_id) VALUES ('Army of Thieves', 1);

